version: '3.8'
services: 
    backend:
        build: ./backend/
        command: bash -c "pip install -r requirements.txt"
        volumes: 
            - ./backend/:/app/frontend/
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
    frontend:
        build: ./frontend/
        volumes: 
           - ./frontend/:/app/frontend

